### ISSUE TITLE
Implement Semantic Release

### ISSUE THREAD

**Issue by nick-woodward** [aguirrel/ng-currency#104]
### Description
https://github.com/semantic-release/semantic-release

### Live Demo
[Example](https://github.com/salte-io/salte-filter/tree/latest)

**Comment by nick-woodward** [comment]
@aguirrel are you fine with me setting up `semantic-release` and `publish-latest` on `ng-currency`?

**It effectively does the following for you:**
* Publishes to NPM
* Publishes your `dist` folder to a latest branch
* Automatically creates release notes

**The caveats are:**
* You have to follow a [commit message format](https://github.com/semantic-release/semantic-release#default-commit-message-format) in order for it to be invoked.

**Comment by aguirrel** [comment]
@nick-woodward yes of course! It's a great improvement! Thanks a lot! :smile:

**Comment by nick-woodward** [comment]
Closed via af232de45a965bfb46918d636abec44565028616
