### ISSUE TITLE
Running test in CI

### ISSUE THREAD

**Issue by aguirrel** [aguirrel/ng-currency#108]
### Description
In previous versions, test were running at CI, but now only build:dist is processed.

### Expected outcome

Both, test and build:dist should be run.

### Actual outcome

[Raw log in CI](https://s3.amazonaws.com/archive.travis-ci.org/jobs/151959327/log.txt)

### Live Demo
https://travis-ci.org/salte-io/salte-filter

### Steps to reproduce

Just go to [CI webpage](https://travis-ci.org/salte-io/salte-filter)

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by nick-woodward** [comment]
@aguirrel That's linked my `salte-filter` repository in the live demo and steps to reproduce.

**Comment by aguirrel** [comment]
haha!! Yes, I did the wrong link, I was learning about semantic release and checking salte-filter CI :smile:
