### ISSUE TITLE
Allow numeric input

### ISSUE THREAD

**Issue by MikeVelazcoMtz** [aguirrel/ng-currency#113]
### Description

Hello, I was trying to use this library with a numeric field and I got an Angular error. I don't know if this is out of the scope of this project but it could be nice that it could be "type independent".

Thank you!

### Expected outcome
Normal operation. Maybe to return the value without the currency symbol.

### Actual outcome

![errorngcurrency](https://cloud.githubusercontent.com/assets/5341310/18901382/0b036f50-8510-11e6-9bea-df77425c3fd5.png)

### Live Demo
https://jsbin.com/juzacuziqo/edit?html,output

### Steps to reproduce

Change the input type to number.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Edge
- [x] Safari 8
- [x] Safari 7
- [x] IE 11
- [x] IE 10

**Comment by aguirrel** [comment]
Hi @MikeVelazcoMtz Please check issue #37. Check [this](http://stackoverflow.com/questions/18939043/angularjs-dynamic-input-type) too.
