### ISSUE TITLE
Show currency symbol at the end of value

### ISSUE THREAD

**Issue by Shigerux** [aguirrel/ng-currency#116]
Hello,

in europe we always have the € sign behind the value. Is there an option to show the currency symbol behind the value instead of the front side?

e.x. 106,13€

Thank you very much. Very nice module!

**Comment by nick-woodward** [comment]
Hey @Shigerux!

`ng-currency` supports Angular's [i18n](https://www.npmjs.com/package/angular-i18n) module.

If you pull it down and import the locale you want, `ng-currency` be formatted to reflect that locale.

Here's a [example](https://jsbin.com/wiguho/1/edit?html,output) that should give you a better idea of what I mean.

**Comment by Shigerux** [comment]
Thank you very much!
