### ISSUE TITLE
Negative input results in () around the formatted value

### ISSUE THREAD

**Issue by ChristianKohler** [aguirrel/ng-currency#120]
First of all, thank you for this great directive. Very well implemented and documented :-)

### Description
When I enter a negative number, the formatted value has () around it

### Expected outcome
-500

### Actual outcome
(500)

### Live Demo
http://jsbin.com/wabapatisa/edit?html,output

### Steps to reproduce
1. Enter -500
2. See (500)

### Browsers Affected
- [ x] Chrome // only tested on chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by nick-woodward** [comment]
Hey @ChristianKohler this change was actually intended, rather then dictating the format of a currency ourselves we delegate to Angular.

**To get the formatting you want there are a couple of solutions to this:**
1. Upgrade to Angular 1.5+ **(Angular changed the default negative currency format to use a `-` rather then `()` post 1.5)**
2. Override the default Currency pattern to format negatives how you'd expect.

### Live Demo
http://jsbin.com/xerususepo/1/edit?js,output

**Comment by ChristianKohler** [comment]
@nick-woodward Thank you for the quick answer :-) 
We already work with ng1.5, i was just trying it out in jsbin with 1.4 since this is the default version in jsbin 1.4. Have a nice weekend.
