### ISSUE TITLE
Ng currency not playing nice with required inputs. 

### ISSUE THREAD

**Issue by mhmaguire** [aguirrel/ng-currency#122]
### Description

required ng-currency inputs arent marked as invalid.

### Expected outcome

required inputs should have class ng-invalid even if pristine / untouched

### Actual outcome

required inputs dont get ng-invalid class until input has been touched and cleared

### Live Demo

https://jsbin.com/podojotoyi/edit?html,output

### Steps to reproduce

1. ng-invalid class is not applied even though the input and model attribute are empty / null
2. Enter a number into the ng-currency input
3. Clear the value
4. at this point ng-invalid is properly applied

### Browsers Affected

Have only checked chrome and firefox

- [x] Chrome
- [x] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by nick-woodward** [comment]
Hey @mhmaguire!

Thanks for taking the time to share this issue!

Seems like `ng-required` works fine, so we just need to take `required` into account as well.

### Live Demo

https://jsbin.com/kavucoqubi/1/edit?html,output

**Comment by mhmaguire** [comment]
No problem, happy to point it out!
