### ISSUE TITLE
ng-required="false" shows min and max error

### ISSUE THREAD

**Issue by chandramuralis** [aguirrel/ng-currency#127]
### Description
   When we have **ng-required="false"** and at the same time if we have **min=500** and **max=3000**, by default ng-currency shows the error on min and max until you enter any value. 

### Expected outcome
If ng-required is false, control should not complain the value is empty. There shouldn't be any error in the control.

### Actual outcome
Setting min and max error as true.

### Live Demo
https://jsbin.com/malevay/edit?html,output

### Steps to reproduce
1. By default the control is treated as error with min and max as error.
2. Start entering any number
3. Clear the value 
4. Now the 'min' and 'max' errors are gone.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 10.0.3
- [x] Opera Developer 44.0
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by nick-woodward** [comment]
@chandramuralis Can you verify that `1.1.6` fixes your issue?

**Comment by chandramuralis** [comment]
Yes! it works.... Thanks @nick-woodward
