### ISSUE TITLE
Update on debounce does not work

### ISSUE THREAD

**Issue by holtc** [aguirrel/ng-currency#130]
### Description
The input is not formatted on debounce, only on blur.  

### Expected outcome

50000 does not turn into $50,000 on debounce.

### Actual outcome

50000 should turn into $50,000 on debounce.

**Comment by nick-woodward** [comment]
### Live Demo

https://jsbin.com/duzeyopose/edit?html,output

### Steps to Reproduce

1. Add a field with a large debounce value
2. Change the fields value
3. Click off of the field
