### ISSUE TITLE
Issues with ng-model-options

### ISSUE THREAD

**Issue by ronnieoverby** [aguirrel/ng-currency#14]
I'm using the new debouncing features of ng-model-options. I noticed that with ng-currency and debouncing that the value in the form field isn't matching the value on the scope.

Here's an example that should reproduce the issue.

 <input type="text" ng-model-options="{ updateOn: 'default blur', debounce: {'default': 500, 'blur': 0} }"
                                                           ng-model="vm.currentItem.amount"
                                                           ng-currency
                                                           required />

**Comment by ronnieoverby** [comment]
Update?

**Comment by aguirrel** [comment]
Again, sorry for the delay, I had some personal issues ;) no update yet. I'm not using angular 1.3 right now, may you write a simple plunk to test the problem so I can fix it?

**Comment by ronnieoverby** [comment]
Sure. I hope everything is okay with you.

-----Original Message-----

**Comment by aguirrel** [comment]
Hi ronnieoverby, yes it's all ok now :) thanks!  Please, may you give me some example to work in?

Best regards,

**Comment by ronnieoverby** [comment]
Here you go: http://plnkr.co/4OsyzyagtV72884uFXlY

**Comment by ronnieoverby** [comment]
Did you see the problem?

**Comment by gomflo** [comment]
the fix is really simple, just add the following:

ngModel.$commitViewValue();

element.on('blur', function () {
            		ngModel.$commitViewValue();
                element.val($filter('currency')(ngModel.$modelValue, currencySymbol()));
            });

**Comment by ronnieoverby** [comment]
Are you going to include that in a new release?

**Comment by aguirrel** [comment]
Hi Ronnie,

Yes I will do some automated test and I will include it in the new release next week.

@gomflo Thanks a lot! ;)

Best regards,

Luis Aguirre

**Comment by aguirrel** [comment]
Hi Ronnie,

Please, update you ng-currency version to v0.8.2 to fix this issue.  If you have any problem please feel free to reopen this ticket.

Thanks!

Best regards.
