### ISSUE TITLE
Wrong number interpretation with German locale

### ISSUE THREAD

**Issue by patsit** [aguirrel/ng-currency#149]
### Description
Entering a number with dots and commas produces wrong outcome.
Note that I am using the German localization (i.e. 1.000,99 instead of 1,000.99)

### Expected outcome
input --> output
100.100.100,20 --> 100.100.100,20
100100100,20 --> 100.100.100,20
100.000 --> 100.000 or  100.000,00
100.000.000 --> 100.000.000 or  100.000.000,00
100000000 --> 100.000.000 or 100.000.000,00

### Actual outcome
input --> output (wrong output is bold)
100.100.100,20 --> 100.100.100,20
100100100,20 --> 100.100.100,20
**100.000 --> 100,00**
**100.000.000 --> 100,00**
100000000 --> 100.000.000,00

### Live Demo

https://jsbin.com/juxafahoji/1/edit?html,output **(provided by @nick-woodward)**

### Steps to reproduce
1. Select German locale
2. Add 
`<input type="text" ng-model="someVariable" ng-currency currency-symbol="" min="1" max="1000000000" fraction="2" />`
3. Enter 100.000.000 to the input field and see that it is changed to 100,00 when clicked outside.

### Browsers Affected
- [x] Chrome
- [x] Firefox
- [x] IE 11
Not able to check:
- [ ] IE 10
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge

**Comment by nick-woodward** [comment]
Confirmed this happens with any locale that uses a `,` for a decimal separator.

### Live Demo

https://jsbin.com/juxafahoji/1/edit?html,output

**Comment by nick-woodward** [comment]
@patsit Can you pull down the latest version of `ng-currency` and verify it fixes your issue?

**Comment by patsit** [comment]
Wow, thank you very much for the very fast fix! Unfortunately I'm not able to test this until end of next week but then I'm going to give you feedback.

**Comment by patsit** [comment]
I can confirm that the bugfix is working! Thank you very much!
