### ISSUE TITLE
"Not A Number" Displayed for values of 20 or 21 digits (within some range)

### ISSUE THREAD

**Issue by ClintLiddick** [aguirrel/ng-currency#16]
When entering a number with 20 or 21 digits the value displayed in the input field is **$NaN.00** (see image). This doesn't seem to happen for values as large as 999999999999999999999 (21 "9's").

```
<div class="col-lg-2">
  <input type="text" id="estCost" class="form-control"
      data-ng-currency data-currency-symbol="$"
      placeholder="Estimated Cost" data-ng-model="ctrl.request.estCost"/>
</div>
```

With 888888888888888888888 (21 8s):
![image](https://cloud.githubusercontent.com/assets/6076080/6085333/d4bb585e-ae06-11e4-9004-554d2fdb38b2.png)

With 999999999999999999999 (21 9s):
![image](https://cloud.githubusercontent.com/assets/6076080/6085345/f124b1d4-ae06-11e4-9212-da65f65c82a1.png)

**Comment by aguirrel** [comment]
Hi ClintLiddick,

ngCurrency is very attached to "currency" filter, which angular version are you using?

**Comment by ClintLiddick** [comment]
Hi Luis,
We're using 1.3.9.

**Comment by aguirrel** [comment]
Hi Clint,

It seems it's working ok with master branch, please check http://plnkr.co/edit/DWgX4S4gi0stf8GPzDwM?p=preview .  Which ngCurrency version are you using?

Best regards,

**Comment by ClintLiddick** [comment]
Hi, sorry for the delay. 
We're using 0.7.10 (file comment with date 2014-11-26). Would updating the file resolve the issue?

Thanks,
Clint

**Comment by aguirrel** [comment]
Hi Clint,

If you use angular 1.2.x please, update to 0.7.11 and tell me if it works without problema.  If you have any problem please reopen this ticket.

Thanks!

Best regards.
