### ISSUE TITLE
Invalid with max + ngRequired + undefined model

### ISSUE THREAD

**Issue by eviljoe** [aguirrel/ng-currency#17]
An ngCurrency text input whose model is undefined is considered to be invalid if it has the following attributes set:
 * `max="[anything]"`
 * `ng-required="true"`

If the model value is `null` or empty string, everything works.  It only breaks if the model value is `undefined`.  If the `required` attribute is used instead of `ng-required` everything works.

Here is a plunker that shows the problem.
http://plnkr.co/edit/n4lFQQTOMwzolYI7SANS?p=preview

**Comment by aguirrel** [comment]
Hi eviljoe,

Please correct me if I'm wrong but it seems this is the expected behavior as if you remove ng-currency and max attributes and just leave it as a standard input validation, you have the same result.

On the other hand, undefined is not a value at all, so  if you ask for a required field you should have this error.

Best regards,

**Comment by eviljoe** [comment]
Yes, the required error is correct, but I am trying to display user-readable errors based on what is exactly wrong in the input field.  The error object has both `required: true` and `max: true` causing both of those error messages to appear on my UI.  I would like the max error to only appear if the input's value is above maximum.

**Comment by aguirrel** [comment]
I will check max error conditions, it should be true if model is null, NaN or undefined.

**Comment by eviljoe** [comment]
Shouldn't it work more like an input[number]?  Null, undefined, and NaN are not considered to voilate the max constraint.  See this plunker:

http://plnkr.co/edit/3B5ZfhChv9dttLGrGnbB?p=preview

**Comment by aguirrel** [comment]
You are right, this is the expected behavior, I will change it and do some test. Thanks!

**Comment by eviljoe** [comment]
Awesome.  Thanks for all your help.  Love this widget!

**Comment by aguirrel** [comment]
Please, update to v0.7.12 to get this problem fixed.
