### ISSUE TITLE
ng-currency doesn't play well with other directives when loosing focus

### ISSUE THREAD

**Issue by tomazy** [aguirrel/ng-currency#18]
My model keeps value in cents but I want the users to edit the value in dollars. I created a simple directive that transforms the value to cents and back. Unfortunately the *onblur* event in your directive assumes that it's the only one on this element and it formats the view value using only the currency formatter. It should transform the modelValue using all $formatters instead.

Look at this demo: http://jsfiddle.net/9kkd9631/ and see what happens when you trigger the *blur* event on the first input.

**Comment by aguirrel** [comment]
Hi @tomazy please, update to 0.8.3.  Thanks a lot!
