### ISSUE TITLE
typo / global leak

### ISSUE THREAD

**Issue by sean-roberts** [aguirrel/ng-currency#22]
`cleaned` is set to null instead of the intended `cleared`

https://github.com/aguirrel/ng-currency/blob/master/src/ng-currency.js#L46

**Comment by aguirrel** [comment]
Hi! you are right! it's even a useless piece of code becouse it was already defined at https://github.com/aguirrel/ng-currency/blob/master/src/ng-currency.js#L32

Thanks a lot!

**Comment by sean-roberts** [comment]
Agreed, which is probably why it not being set to null -- because of the typo -- was never an issue. Glad I could help!

**Comment by sean-roberts** [comment]
clicked wrong button :wink:

**Comment by aguirrel** [comment]
Please, update to version 0.7.14 or 0.8.4 depending on you angular version. Thank you!
