### ISSUE TITLE
Decimal places

### ISSUE THREAD

**Issue by xnog** [aguirrel/ng-currency#25]
Does it support more than two decimal places?

**Comment by xnog** [comment]
I had to put fraction="5" but didn't work.

Changing from:
function clearRex(dChar) {
     return RegExp("\\-{0,1}((\\" + dChar + ")|([0-9]{1,}\\" + dChar + "?))&?[0-9]{0,2}", 'g');
}

to:
function clearRex(
     return RegExp("\\-{0,1}((\\" + dChar + ")|([0-9]{1,}\\" + dChar + "?))&?[0-9]{0," + scope.fraction + "}", '
}

works.

**Comment by xnog** [comment]
return RegExp("\-{0,1}((\" + dChar + ")|([0-9]{1,}\" + dChar + "?))&?[0-9]{0," + scope.fraction + "}", 'g');

**Comment by aguirrel** [comment]
Hi @xnog I'm checking it.  Thanks!

**Comment by aguirrel** [comment]
This issue is fixed, it's available in v0.8.x branch and in next release this week.

**Comment by aguirrel** [comment]
Please, update to v0.8.6 and feel free to reopen this ticket if you have any problem.

**Comment by Matmo10** [comment]
Can the fraction value be changed dynamically?

**Comment by nick-woodward** [comment]
@Matmo10 Yup, you can use a binding to change it dynamically.

### Example

**[Live Demo](https://jsbin.com/panehugaci/1/edit?html,output)**

### Snippet

```html
<input type="text" ng-currency ng-model="value" fraction="{{fraction}}">
```
