### ISSUE TITLE
Field value empties when invalid

### ISSUE THREAD

**Issue by StrayAlien** [aguirrel/ng-currency#26]
Here is the behaviour I see.  On 0.8.5.  I believe it is from something introduced in 0.8.3.

If a field has (say) a min and / or max range and you tab off it while it has an invalid value the field value is set to blank.

The reformatViewValue() function is run after a $commitViewValue and gets the $modelValue and runs the formatters over it and then sets the view value.  I suspect $commitViewValue does not actually commit the value from the view to the model if there are validation failures.  So, ngModel.$modelValue is actually undefined if the field view value fails validation  .. meaning the formatters are executed on an undefined value, and that undefined value then becomes the new view value.  Stuff goes blank then.

Perhaps consider using the $viewValue in reformatViewValue() rather than $modelValue?

**Comment by aguirrel** [comment]
Hi @StrayAlien I'm checking it.

**Comment by aguirrel** [comment]
Please, update to v0.8.6 and feel free to reopen this ticket if you have any problem.

**Comment by StrayAlien** [comment]
Thanks @aguirrel.  That has resolved the issue.  Actually, it has also fixed another issue that an amount outside the min/max range (that is, failing validation) was not formatted with the currency sign and thousands separators. 

Thanks again.
