### ISSUE TITLE
used in a form, $dirty is not set on the input

### ISSUE THREAD

**Issue by adrianbader** [aguirrel/ng-currency#27]
I like to use ng-currency in a form. According to the $dirty states, I send the changed values to the backend on form submit. The form itself is set to $dirty, but the input itself, on which ng-currency is applied, is not set to $dirty... I quickly checked, if I can find the issue, but did not succeed. Can sombody check that? - Thanks in advance!
(I am using version: 0.8.6)

**Comment by aguirrel** [comment]
Hi @adrianbader I will check it!

**Comment by aguirrel** [comment]
Hi @adrianbader , I tested it and it works fine.  Could you send me an example?

Thanks a lot!

Best regards,

Luis Aguirre

**Comment by aguirrel** [comment]
Please, use v0.8.7 if you do the example ;)

**Comment by adrianbader** [comment]
Hi aguirrel. Thank you for the feedback. I tried to make a minimal example showing the issue. After creating the minimal example, I remarked, that it really works fine. Sorry for this false alarm - the issue is in the rest of my project then (I have some more directives applied to the input using ng-currency). Thanks a lot for your work!
Best regards,
Adrian
