### ISSUE TITLE
min value validation ignored on blur for negative numbers

### ISSUE THREAD

**Issue by panteln** [aguirrel/ng-currency#29]
Hi. Currently using ng-currency on an input element like this:

```<input id="input-paymentAmount" type="text" name="amount" ng-model="model.amount" ng-currency currency-symbol="$" required min="1.00" max="9999999.99"/>```

If I enter a negative value (eg. -20), ng-invalid-min is set as expected while focussed but if I tab out of the field the validation is reverted back to ng-valid-min (which is incorrect).

Interestingly this only occurs for values <= -1 (in this instance). If i enter a value between -1 and 0 the validation works as expected. If I change the min value above to, say, 10 then the problem exists for values <= -10 but all values between -10 and 0 validate correctly.

Using ng-currency v0.8.6, angularjs v1.3.15
I would really appreciate it if you had a moment to investigate this.

Many thanks in advance

**Comment by aguirrel** [comment]
Yes, It was a problem with negative values and parser.  Should be corrected in next version. Thanks a lot!

**Comment by aguirrel** [comment]
Please, try with v0.8.7 and feel free to reopen this ticket if it doesn't work. Thanks!

**Comment by panteln** [comment]
That appears to have fixed it. Many Thanks!
