### ISSUE TITLE
The Plunker example is broken

### ISSUE THREAD

**Issue by seibar** [aguirrel/ng-currency#34]
Loading up the Plunker (http://plnkr.co/edit/u9mJqDH8UpwxDnOv8gZL?p=preview), there is an error in the console right away:
`TypeError: Cannot set property 'min' of undefined`

And then on blur of the input, there is another error:
`Uncaught TypeError: ngModel.$commitViewValue is not a function`

**Comment by aguirrel** [comment]
Hi @seibar,  Yep! I changed master branch to 0.8.x and this broke plunker, I fixed it! Please try again and if you find any issue please feel free to reopen this ticket!

Thanks a lot!
