### ISSUE TITLE
Not working with type="number"

### ISSUE THREAD

**Issue by simkepal** [aguirrel/ng-currency#37]
Hello, 

great directive. It always removes values if I have type="number". I want to have number type so on the smart phones shows only numeric keyboard. Is it possible to fix this?

Thank you!

Regards,
Simon

**Comment by aguirrel** [comment]
Hi @simkepal, I think is not possible as this directive adds currency symbols to the input field, so it will never be a "valid number" itself. ;)

If you don't need any currency symbol, you can try using type="number" step="0.01" for example.

**Comment by simkepal** [comment]
Hi @aguirrel,

I don't need currency symbol, but I want number to be in 1.234.567,89 format. And your directive is working great for me, except that. It also adds decimal zeros if user does not insert them. Do you have any other idea, how to do this?

Thank you!

**Comment by aguirrel** [comment]
Hi @simkepal, I think you can't get a format like that in a number input becouse it doesn't accept "," nor "." symbols in the currency way, I did a plunk for you configuring ng-currency to not use any currency symbol:

http://plnkr.co/edit/OLOpjbnPJdnThTyHvskK?p=preview

If you find some solution or idea please share here ;)

Thanks a lot!

Best regards.

**Comment by aguirrel** [comment]
Hi @simkepal,

Did you do it in some way? Or you had to let in "text" type?

Thanks!

**Comment by simkepal** [comment]
Hi @aguirrel 

I did not do anything, I did not have time. For now is just text type. If you find any solution please let me know. :))

Thank you!

**Comment by aguirrel** [comment]
I'm checking how you could do that, I did a plunkr changing type on the fly but seems ng-currency fails on show formated currency.  One thing to take care is only dot "." is allower, if your currency use coma "," as decimal separator gets worse :S 

I will check it, I'm doing an webapp that could be very cool to have this feature ;)

**Comment by aguirrel** [comment]
I have just checked as enhancement to not lost it ;)

**Comment by vjanssens** [comment]
Hi guys, to force numeric keyboard on `type="text'` inputs this SO answer may be a good solution http://stackoverflow.com/a/6512618/1323800. I haven't tested it myself but this may be the thing you need.

**Comment by aguirrel** [comment]
Hi @vjanssens , main problem here is currency symbol and separators (',', '.', etc.).  When you set it numeric or using a pattern to show only numeric pad, you get an error.
