### ISSUE TITLE
Add Support of commonjs (Browserify)

### ISSUE THREAD

**Issue by mehdivk** [aguirrel/ng-currency#38]
It would be great if repo comes with a `package.json` and module be compatible with `Browserify`, even better if you could publish a version of module to `npm` as well.

**Comment by aguirrel** [comment]
Hi @mehdivk please update to version 0.8.8! 

Thanks a lot!

Best regards,

Luis

**Comment by mehdivk** [comment]
Hi,
Thanks for merging PR, will you publish the module in NPM as well? I checked it today and can't find it under `ng-currency` name

**Comment by aguirrel** [comment]
You are right!  I have just added it to npm: https://www.npmjs.com/package/ng-currency

Thanks a lot!

Best regards.
