### ISSUE TITLE
ng-model initially set and currency-symbol attribute - initially currency symbol doesn't refresh to valid. 

### ISSUE THREAD

**Issue by pacior** [aguirrel/ng-currency#40]
Hello this is my first post to github. I found a bug. When i set ng-model to value in app controller and use ng-currency with currency symbol in input box, currency symbol initially is not set. 
It works after clicking on input, so touch event is called. 
I tried changing sequence in html input attribute, so ng-currency-symbol=" " went before ng-model. 
I see the solution in my app by forcing click on input after page loads. Quite, it seems unellegant and doesn't solve problem for other users. 
How can i repair this? I would like to have my first contribution to github by adding a patch to this code fixing this, but i don't know how to do this( forks, pull requests, commits). Is there any faq to this?

**Comment by aguirrel** [comment]
Hi @pacior!

Welcome to github collaboration! :) Could you send me some relevant code so I can check it? If you need to submit a patch you should fork the project, clone it in your pc, do modifications, commit and push to your repository, then go to github and do a "PR" or "Push Request", here you have more information: https://help.github.com/articles/using-pull-requests/

Thanks!

**Comment by pacior** [comment]
I have ng-repeat that is updated in another ng-repeat, so i have table with rows and adding row to a table creates a form in which you can add subrows of parent row. And in this row there are fields with ng-currency directives. First i'll paste some chunk of codes so it should stay clear: 
1) I am running function after adding row, to init $scope.params.podtowar[tIndex].Qty field which is 1 usually. 
`$scope.params.podtowar[tIndex].Qty = $scope.towaryEntries[tIndex].Qty;`
2) The subform generated on each row, column with Quantity looks like: 
`<input width="55" style="width: 55px" id="ilosc{{$index}}" name="ilosc{{$index}}" placeholder="Quantity" ng-currency currency-symbol=" " max="9999999999" ng-model="params.podtowar[$index].Qty" ng-pattern="PricePattern">`

The problem is that initially it is 1.00 zł and should be 1.00. 
1.00 appears when i click on input and then click somewhere else.

**Comment by aguirrel** [comment]
Yes, I can reproduce it at: http://plnkr.co/edit/nF7KWjuvub3UtY4YdCCP?p=preview

I'm checking it! Thanks!

**Comment by aguirrel** [comment]
Please, update to ng-currency v0.8.9.

Main problem was angular parameter, if you do currency-symbol=" ", angular take it as empty, so currency symbol was undefined inside directive, please use: currency-symbol="{{' '}}" to get it right.

Feel free to use http://plnkr.co/edit/nF7KWjuvub3UtY4YdCCP?p=preview as sandbox ;)

If you need further assistance about this issue, please reopen it.
