### ISSUE TITLE
Input value disappear on blur

### ISSUE THREAD

**Issue by pacior** [aguirrel/ng-currency#41]
In version 0.8.9 and 0.8.8 when I place 22 in input and click outside, value disappears. 
Code: `<input required width="75" style="width: 75px" id="quantity" name="quantity" placeholder="quantity" ng-model="params.towar.qty" ng-pattern="CenaPattern" ng-currency currency-symbol=" " max="9999999999">`
I tried with currency symbol {{' '}}
Everything works in 0.8.4 version.

**Comment by aguirrel** [comment]
Hi @pacior It seems to work fine in http://plnkr.co/edit/T8YvF59DVQCp9VpOdV82?p=preview

Could you send me "CenaPattern" in ng-pattern, is the only thing that I don't have to full reproduce it.

Thanks!

**Comment by pacior** [comment]
CenaPattern in english is PricePattern
    $scope.PricePattern = (function() {
    var regexp = /^[0-9]{0,13}[\.]{0,1}[0-9]{0,2}$/;
    return {
        test: function(value) {
            if( $scope.requirePassword === false ) {
                return true;
            }
            return regexp.test(value);
        }
    };
})();

**Comment by aguirrel** [comment]
mmm... I's working fine to me: http://plnkr.co/edit/T8YvF59DVQCp9VpOdV82?p=preview

Could you send me which browser and version are you using to test it? If you go to plunker, does it work for you?

**Comment by pacior** [comment]
Yes it works fine in same browser. I have Angular 1.3.3 maybe this is issue?

**Comment by aguirrel** [comment]
Yes! It seems that version 1.3.3 is the problem, please, upgrade to 1.3.4 or above and check it again.

**Comment by pacior** [comment]
It works fine in 1.3.4. 
Thank You

**Comment by aguirrel** [comment]
You're welcome!
