### ISSUE TITLE
When having negative numbers, value of ng-model is undefined. 

### ISSUE THREAD

**Issue by pacior** [aguirrel/ng-currency#42]
When in html input like this: `<input type="text" width="55" style="width: 55px" id="CostAmount{{$index}}" name="CostAmount{{$index}}" placeholder="Price" ng-model="params.podtowar[$index].CostAmount" ng-pattern="PricePattern" ng-currency max="9999999999">`
In Angular version 1.3.4 and ng-currency 0.8.9 i type negative number like -10 it formats to (10) which is fine, because so are defined negative prefixes and suffixes, but ng-model when i type negative number is undefined. I expect it to be -10.

**Comment by aguirrel** [comment]
I'm checking it!

**Comment by pacior** [comment]
I don't know if it is a bug in my app or no, but made some reading about your code and what i have found is that ngModel.parsers function returns correct value for negative number. for -11 it returns -11. But somehow in my ng-model value is undefined for negative numbers. It is correct for positive numbers. I have (11) for expressing negative value set.

**Comment by aguirrel** [comment]
Hi!

It seems that error is in PricePattern as it doesn't work well with negative symbol, please repleace:
<pre>
var regexp = /^[0-9]{0,13}[.]{0,1}[0-9]{0,2}$/;
</pre>

and add "-{0,1}" to the front of regexp:

<pre>
var regexp = /^-{0,1}[0-9]{0,13}[.]{0,1}[0-9]{0,2}$/;
</pre>

You can check it at http://plnkr.co/edit/T8YvF59DVQCp9VpOdV82?p=preview

Feel free to reopen the ticket if you have any problem ;)
