### ISSUE TITLE
Setting default value after emptying input box

### ISSUE THREAD

**Issue by pacior** [aguirrel/ng-currency#43]
When having ng-model connected to input with ng-currency directive in version 0.8.9 and Angular 1.3.4. 
When I type number in input and then remove it ( by hitting backspace ) ng-model associated has NaN value. Is it expected behaviour?

**Comment by aguirrel** [comment]
Hi! Yes this is the expected behaviour as NaN means "Not a Number", and is more informative than undefined or null.  Is the same as when you remove all numbers and start writing words. ;)

**Comment by aguirrel** [comment]
Please, feel free to reopen this issue if you need further information.
