### ISSUE TITLE
Min/Max Validation does not fire after updating the min/max values

### ISSUE THREAD

**Issue by holtjonathan** [aguirrel/ng-currency#45]
Hello,

Please take a peek at this jsbin: http://jsbin.com/vaxupud/edit?html,js,output

Enter 5 in both fields and then press the `Change min/max` button.  Notice how the normal number field auto validates as being below the new `min` value but the ngcurrency field does not.  It seems that the validation for ngCurrency does not re-validate upon the min/max values changing.

**Comment by aguirrel** [comment]
Hi! Great example! Yes, ng-currency does not re-validate when min and max are changed.  I will modify it.  Thanks!

**Comment by holtjonathan** [comment]
Great!  I am looking forward to it.  I want to use ngcurrency but this issue requires me to use a different way of going about checking ranges that update.  Not to rush you...but any idea when this could get pushed?

**Comment by aguirrel** [comment]
Done! Please, update to version 0.8.10. ;)  Feel free to reopen this ticket if you have some issue.

**Comment by aguirrel** [comment]
I'm checking your example, seems not working.  It seems that when ng-currency loads min and max are undefined.  Could you check it?

**Comment by aguirrel** [comment]
Ok, re-implemented.  Now http://jsbin.com/vaxupud/edit?html,js,output is working fine! ;)

Please, update to 0.8.11 and feel free to reopen this ticket if you have some issue.

**Comment by holtjonathan** [comment]
Sorry @aguirrel, I was at an away wedding all weekend.  The change looks great!  Thanks again for the quick turnaround!

**Comment by aguirrel** [comment]
Hi @holtjonathan! No problem! Please, feel free to reopen this ticket if you need further assistance.

**Comment by holtjonathan** [comment]
Hey @aguirrel 

Follow up question.  I modified my example to be this: http://jsbin.com/woditupeya/1/edit?js,output

I am setting the field to a default (simulating that the data is gathered from a service or something).  The min/max validation is not kicked off until I click into the field itself.

I don't know how to reopen this ticket tho :(

**Comment by aguirrel** [comment]
Hi @holtjonathan I'm checking it :)

**Comment by aguirrel** [comment]
Validation are triggering fine, please see that ng-invalid ng-invalid-min are set in input, but seems that message is not trigger until ng-touched is set, and that happend on blur.

Peharps you should trigger message on invalid and not depend on touched too?

**Comment by holtjonathan** [comment]
Wow, I feel stupid.  LOL

Sorry about that.  Everything looks totally fine on the ng-currency side of things.  My bad :)

**Comment by aguirrel** [comment]
haha! No problem.  Please reopen this issue if you need further assistance. ;)
