### ISSUE TITLE
currency-symbol

### ISSUE THREAD

**Issue by Sevensnake** [aguirrel/ng-currency#46]
can you switch the currency symbol from left to right??

**Comment by aguirrel** [comment]
Hi @Sevensnake,

This directive depends on locale configuration, please check http://plnkr.co/edit/u9mJqDH8UpwxDnOv8gZL?p=preview 

Pay special attention to:
<pre>
  <script src="https://code.angularjs.org/1.4.3/i18n/angular-locale_es-ar.js"></script>
</pre>

If none of i18n fits your requirements feel free to generate a custom one, is very easy.

Please do noy hesitate to contact me if you need further support.

Best regards.

**Comment by ranstyr** [comment]
it can be great if you could please provide working example for it?
