### ISSUE TITLE
Model value is incorrectly floored when fraction is changed dynamically

### ISSUE THREAD

**Issue by omnibrain** [aguirrel/ng-currency#47]
First, let me thank you for this creating this useful module! I found a (minor, yet for my application severe) bug though:

I noticed that the model value is incorrectly rounded to the *initial* fraction instead of the *current* fraction.

[I created a Plunker to illustrate the bug](http://plnkr.co/edit/nYVvdzJv4iOaRPgL3V0q?p=preview)

As you can see in the plunker, the "fraction" attribute of the input is bound to $scope.fraction. The decimal places are correctly displayed after $scope.fraction is changed to 5, but if you enter a value in the input field, eg. 0.0001, the value is rounded (actually floored) to 2 decimal places, the *initial* value of the fraction attribute. So the $scope.testVariable is now still 0 if I enter any value smaller than 0.01, even though the input field displays 5 decimal places.

**Comment by aguirrel** [comment]
mmm... it seems pretty odd. I will check it next week, if you are in a hurry please tell me.

Best regards,

Luis

**Comment by aguirrel** [comment]
Really sorry for this delay, please, update to version 0.8.12 to fix this issue.

If you have any problem do not hesitate to reopen this ticket.

Thanks!

Best regards,

Luis

**Comment by omnibrain** [comment]
No problem at all! Thanks for the fix, seems to work fine.
