### ISSUE TITLE
reset to $$rawModelValue when input on focus

### ISSUE THREAD

**Issue by yingjun** [aguirrel/ng-currency#48]
element.on('focus',function(){
                  ngModel.$setViewValue(ngModel.$$rawModelValue || '');
                  ngModel.$render();
        				});

it is not an issue just want to add this feature, when focus on the input rest to raw model value so that easy to modify the value.

**Comment by aguirrel** [comment]
Hi @yingjun, I wrote it in code.  Please upgrade to 0.9.1 to get this feature.  Thanks a lot!
