### ISSUE TITLE
Bower install fails

### ISSUE THREAD

**Issue by immortalcy** [aguirrel/ng-currency#49]
On your documentation you mention that for angular > 1.3.x we can use version 0.8.x.
I tried almost all the versions and all I am getting is:

`bower ECONFLICT Unable to find suitable version for angular`

Would you know anything on this issue ?

**Comment by aguirrel** [comment]
Yes it is, you can check this stackoverflow question about this problem:

http://stackoverflow.com/questions/25915729/unable-to-find-a-suitable-version-for-angular-bower-install

Please try to resolve it using:

  "resolutions": {
    "angular": "~1.3.x"
  }

In your bower.json, feel free to reopen this ticket if you need further assistance.

**Comment by immortalcy** [comment]
Will that have any conflicts with packages that are not angular 1.4.x compatible ?

**Comment by aguirrel** [comment]
I don't know which packages you are using.  ng-currency works with angular 1.4.x without any problem.  Actually I use 1.4.x.  Please check documentation for packages.  Many packages works fine even if there are not 1.4.x specific.

**Comment by immortalcy** [comment]
This is how my bower.json file looks like:

`"angular": "^1.4.0",
    "angular-animate": "^1.4.0",
    "angular-aria": "^1.4.0",
    "angular-cookies": "^1.4.0",
    "angular-messages": "^1.4.0",
    "angular-resource": "^1.4.0",
    "angular-route": "^1.4.0",
    "angular-sanitize": "^1.4.0",
    "angular-touch": "^1.4.0",`

That is why I couldn't understand the error since you specify here that your module works on angular 1.3 +

Anyhow I got it working now by adding:
`"resolutions": {
    "angular": "^1.4.0"
  },`

I just wasn't sure if this would overwrite any other decencies for future modules that I will be installing.
Sorry for all this -- just started using bower 1 and a half months ago!!

**Comment by aguirrel** [comment]
Ah! ok, I understand, ng-currency dependency is 1.3.x not 1.3+ and all your packages are for 1.4.x, this is why you are asked for resolution.  I will update package dependency in next release, in the meantime "resolution" item do the trick.

Thanks!

**Comment by immortalcy** [comment]
Great... thanks :)
Will keep in mind to remove it on the net bower update !!
