### ISSUE TITLE
How to remove Currency Symbol?

### ISSUE THREAD

**Issue by bbugs280** [aguirrel/ng-currency#5]
Hi, this is a great lib for my app. But is there a way to remove the currency symbol?

**Comment by salvarubiomartinez** [comment]
Hi!
How can I force the currency type to be always in dollars format and not European?
Always 9,999,999.99 and not 9.999.999,99 despite of the locale settings in browser.

**Comment by nick-woodward** [comment]
I believe the locale settings are provided by Angular, not the browser.

https://jsbin.com/rogahesuhe/edit?html,output
