### ISSUE TITLE
error: $compile:nonassign

### ISSUE THREAD

**Issue by javo01** [aguirrel/ng-currency#51]
Hi i'm using ng-currency, and in my dev machine everything works fine, but when i upload my project to the server it shows me this error:

Error: [$compile:nonassign] http://errors.angularjs.org/1.3.20/$compile/nonassign?p0=undefined&p1=ngCurrency

i'm using the directive like this:

`<input type="text" class="form-control" aria-label="Sale price of the property" ng-model="property.salePrice" id="salePrice" ng-currency />`

and this is a caption of the error:

![image](https://cloud.githubusercontent.com/assets/4388505/11913800/3075d3ea-a636-11e5-99d1-8c5561cd02d9.png)

**Comment by aguirrel** [comment]
Hi @javo01, Please check that ng-currency files are available and correctly installed.

**Comment by javo01** [comment]
it's installed:

![image](https://cloud.githubusercontent.com/assets/4388505/11939001/6c300dce-a7e4-11e5-8292-13afa24c9a88.png)

and it's accessible, this is the file in the previous link:
![image](https://cloud.githubusercontent.com/assets/4388505/11939018/84376034-a7e4-11e5-92be-1997b78ce9ee.png)

i never had an issue before with ng-currency, and i couldn't figure out what was the problem so i ended here

**Comment by aguirrel** [comment]
If you use regular ng-currency.js instead of minified one, does it work well?

**Comment by javo01** [comment]
nop, i tried, it's the same :/

**Comment by aguirrel** [comment]
I checked your code and seems ok, could you send me your app location to check it online? you could send it to me using my email if you want.

**Comment by javo01** [comment]
of course, luis@alaguirre.com right?

**Comment by aguirrel** [comment]
yes please.

**Comment by ogousa** [comment]
Make the binding optional. You should change parameters in ng-currency.js:
           scope: {
                min: '=?min',
                max: '=?max',
                currencySymbol: '@',
                ngRequired: '=?ngRequired',
                fraction: '=?fraction'
            },

**Comment by aguirrel** [comment]
Thanks @ogousa! I changed it in code.  Please, upgrade to v0.9.1 and reopen this ticket if you still have this issue.
