### ISSUE TITLE
Both dot and comma separators probably should be treated as decimal separators

### ISSUE THREAD

**Issue by einars** [aguirrel/ng-currency#53]
Currently, if the locale setting is to use decimal comma, then typing "0.50" in the input transforms it into "50,00", and that's quite bad.

I patched it locally so that the decimalRex and clearRex would use a separator regex, and pass the default of '[\.,]' — it works beautifully for my needs, but I'm not sure if that's i18n enough.

**Comment by aguirrel** [comment]
Hi @einars,

mmm.. I'm not sure for that.  If I type 050 I expect a $50.00.  If I type .5, or .50 I expect $0.50.  Just like any calc would do in those decimal cases.

Best regards.

**Comment by einars** [comment]
Well, that's exactly what I'm saying: if I type 0.50 or .50, I expect $0,50, even if my locale has decimal comma. Currently it transforms to $50.

To repeat, right now, under my locale, typing ".50" in the plunger demo, yields $50 with a model value of "50".

**Comment by aguirrel** [comment]
I'm really sorry, I misunderstood you.  Yes I think this could be the correct behaviour if we connect this with issue #48 as when in focos you will only see '.' as decimal comma.  I will do this change for next version 0.9.x, hopefuly for today ;)

**Comment by aguirrel** [comment]
Please, upgrade to 0.9.1 and reopen this ticket if you have any issue.  Thanks!

**Comment by einars** [comment]
Yup, works great!

**Comment by loomismilitia** [comment]
Hi there,

I've installed the latest version 1.2.5 and this issue persists.
It's supposed to be the default behavior for the most recent versions? 

thank you
