### ISSUE TITLE
rawModelValue formatting

### ISSUE THREAD

**Issue by einars** [aguirrel/ng-currency#54]
The new "raw model on focus" feature from #48 gives some unfortunate drawbacks:

1. having actual "0.00" (as a specific 0.00, not null, not Nan, not undefined) amount, the amount completely disappears as not entered at all on re-focusing;

2. it's not exactly "raw" value: if i've entered "0.40", I'd probably expect to see "0.40". Instead the leading zeroes are stripped, and I have to visually confirm if what I'm editing is what I actually intended to.

I suppose that the feature was intended to allow editing the amount without the currency symbols messing up the input: this would better be achieved by displaying formatted amount, just without currency or thousand markers:

$123.456,78 → (currently) 123456.78 → (i suggest) no change,
$123.456,70 → (currently) 123456.7 → (i suggest) 123456.70
$123.456,00 → 123456 → 123456.00
$0.00 → Nan → 0.00

This way, the user would always know what to expect from the input.

**Comment by aguirrel** [comment]
Yes, it's a good idea!  Please update to 0.9.2 to get this behaviour.
