### ISSUE TITLE
Possiblity to add onBlur event?

### ISSUE THREAD

**Issue by burakkilic** [aguirrel/ng-currency#55]
Hi;

I want to use the input lie a content editable. If there would be a onBlur event callback, I could do this.

Thank you.

**Comment by aguirrel** [comment]
Hi! Couldn't you use ng-blur in input tag?  Do you need something internal from directive?

**Comment by burakkilic** [comment]
Thank you, I will try it.

**Comment by aguirrel** [comment]
Hi @burakkilic please reopen this ticket if you need further assistance.
