### ISSUE TITLE
Wrong formatting on fraction=0

### ISSUE THREAD

**Issue by adnjeremy** [aguirrel/ng-currency#56]
When you blur/focus, the formatted value is incorrect

check out this plinker: http://plnkr.co/edit/FZW6dFyVKckO5QICN5XQ?p=preview
and try blurring.

what i can see is that the $$rawModelValue (in the focus event ) is not giving the correct value.

**Comment by aguirrel** [comment]
Hi @adnjeremy I'm checking it.

**Comment by aguirrel** [comment]
I'm checking it, I fixed fraction=0, but for some reason, after two blur/focus, number gets negative, but only with nl i18n!

**Comment by aguirrel** [comment]
Checked and modified how directive searchs for negative number in currency.

**Comment by aguirrel** [comment]
Please, update to v0.9.3.
