### ISSUE TITLE
currencyRedraw

### ISSUE THREAD

**Issue by TommiTikall** [aguirrel/ng-currency#60]
Hello @aguirrel 

Very nice directive :)

I am missing the "currencyRedraw" $broadcast listener, as mentioned in the documentation.
It isn't in the directive and it's an important feature, to be able to update input fields when changing locale dynamically.
I have added it my self, but I think it would be nice for others if it was included.

**Comment by aguirrel** [comment]
Hi @TommiTikall Thanks! currencyRedraw is already in code and is working well AFAIK.  Please, try using $broadcast() or $emit().  Try again and if it doesn't work please send me steps you are doing to try to reproduce it ;)

**Comment by TommiTikall** [comment]
That I can see now.. The file I have from npm install is "Version: 0.8.8 - 2015-09-17" and is not the same as the file in your repo. I don't understand that. And your package.json file refers to the correct version.. I have no idea how this happened. The local package.json I have is 0.8.8.

**Comment by aguirrel** [comment]
Hi @TommiTikall Last 0.8.x version is 0.8.12. Please uninstall this packege and reinstall it and check your development dependencies, perhaps you added an especific version instead of "~version".  Please, reopen this ticket if you need further assistance.
