### ISSUE TITLE
Error if max is a scope value.

### ISSUE THREAD

**Issue by alain-andre** [aguirrel/ng-currency#61]
Hi, I need my max attribute to be set by the scope and it fails. Cf. [plunker](
http://plnkr.co/edit/K05GFkiWaIaHXTh5nHT0?p=preview)

`Error: [$parse:syntax] Syntax Error: Token '{' invalid key at column 2 of the expression [{{max}}] starting at [{max}}]`

**Comment by vjanssens** [comment]
Hi Alain, I see you're using `max="{{max}}"`, but you can just use `max="max"`. This will fix your problem.

**Comment by aguirrel** [comment]
Thanks @vjanssens ! Please reopen this ticket if you need further assistance.

**Comment by alain-andre** [comment]
OK, thanks, It works, but it cannot be a complex object (like a `$scope.thing.max`) I had to store it in a `$scope.max`.

**Comment by aguirrel** [comment]
Hi @alain-andre, it doesn't matter if object is complex or not, please check http://plnkr.co/edit/DUJ5hI4aB7cOatjV3Ygp?p=preview to see an example using $scope.thing.max ($scope.testModel.max in this case).

I think you should check not asigning another object to $scope.thing, becouse you can loose childs to be checked by angular digest.  Try to use deepcopy instead.
