### ISSUE TITLE
Input Exceeds Max Length on Blur Resulting In Undefined ngModel

### ISSUE THREAD

**Issue by samuelhopkins** [aguirrel/ng-currency#63]
If a maxlength attribute is specified for an input and on focus the input length reaches the maxlength value, on blur the addition of commas or decimal zeros may push the input length over the specified maxlength at which point the variable bound by ng-model defaults to undefined.

**Comment by aguirrel** [comment]
Hi @samuelhopkins , thanks for reporting.  Is it possible for your use case to use "max" instead of maxlength?  This should work much better, currency is in the middle of number and string and sometimes doesn't work well mixing things.

**Comment by aguirrel** [comment]
Please reopen this ticket if you need further assistance.
