### ISSUE TITLE
On focus pre-populating with 0.00

### ISSUE THREAD

**Issue by fauda** [aguirrel/ng-currency#64]
When you focus it pre-populates the input with 0.00

Looks like this was changed recently in #58 (line 170)

I've rolled back to v0.9.2 as this is undesirable behaviour and I can't imagine others would want this either as it creates a weird flow.

**Comment by aguirrel** [comment]
Hi @fauda You are right.  This unexpected behaveur was introduced in v0.9.3, I will check it and came back.

Thanks!

**Comment by dockinkong** [comment]
Hi, I'm facing same issue, and using v0.9.2 I'm having problems with undefined values as in "element.on('focus', function () {" part, null value is not treated. You probably should not set value to '0.00' if viewValue is not defeined... or having new param to set default value.

Hope this helps,

Regards.

**Comment by aguirrel** [comment]
Yes, seems that #58 introduced some bugs, I'm checking it.

**Comment by fauda** [comment]
Thanks, that commit did seem a little strange

**Comment by acesaft** [comment]
how's this issue tracking?

**Comment by aguirrel** [comment]
I have rolled back this PR and I will do a release today without this.  Then I will take more care about this feature that I think is interesting to have.

**Comment by aguirrel** [comment]
Please, update to 0.9.4 to have fix it.
