### ISSUE TITLE
Unable to instantiate ng-currency 

### ISSUE THREAD

**Issue by jkeczan** [aguirrel/ng-currency#67]
Seems that something may have changed. Have started getting the following error, without any code changes:

```
Error: [$injector:modulerr] Failed to instantiate module ng-currency due to:
Error: [$injector:nomod] Module 'ng-currency' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
```

Any thoughts? Potential upgrade in Angular?

we are using the cloudflare CDN.

**Comment by aguirrel** [comment]
Hi! I don't know what could be happening because I don't know who is maintaining cloudflare copy.  Please download this repository or use bower to install this directive and give it a try.  If the problem persists please ropen this ticket.

Thanks!
