### ISSUE TITLE
Dist not actualized

### ISSUE THREAD

**Issue by RodolfoRb** [aguirrel/ng-currency#70]
Hi,
the version 0.9.5 

has a change on focus function 
                    if(isNaN(viewValue) || viewValue === '' || viewValue == null)
                    {
                        viewValue = '';
                    }
but, the folder dist  hasn't changes this occured when i install the new version. maybe the relese has a problems.

in dist continue saied 
                        viewValue = '0.00';

thanks for all :+1:

**Comment by aguirrel** [comment]
Hi @RodolfoRb you are right! Please update to 0.9.6, it seems that I tagged version 0.9.5 before pushing changes.

Thanks a lot!
