### ISSUE TITLE
Avoid using isolated scope

### ISSUE THREAD

**Issue by dockinkong** [aguirrel/ng-currency#75]
Hello,

I'm using your directive which workes fine, but I'm facing an issue adding an other one with isolated scope to my element. Could you try some changes  with a new scope instead of isolated one?

```
...
 require: 'ngModel',
 scope: true,
 link: function (scope, element, attrs, ngModel) {
                scope.min=attrs.min;
                scope.max=attrs.max;
                scope.currencySymbol=attrs.currencySymbol;
                scope.displayZeroes=attrs.displayZeroes;
                scope.ngRequired=attrs.ngRequired;
                scope.fraction = attrs.fraction;
...
```

Regards,

**Comment by aguirrel** [comment]
Hi @dockinkong if you do this changes at your ng-currency local copy, does it work? Sorry for the delay.

**Comment by dockinkong** [comment]
Yes it does.

**Comment by aguirrel** [comment]
mmm... It really seems as a hack for me, please correct me if I'm wrong but it doesn't seem as a good practice.  I can't find any documentation about it. Couldn't you just change attributes dinamically and call $broadcast("currencyRedraw") if you need to see changes inmediatly?

**Comment by dockinkong** [comment]
I'm just facing an issue because your directive defines an isolated scope on the element wich doesn't allow the usage of an other directive wich also uses an isolated scope. I only proposed to use new scope instead (scope: true), getting attributes to store them in the scope wich I think is not a bad practice.

**Comment by aguirrel** [comment]
Ok, after a more deep search I found this [article](http://www.bennadel.com/blog/2729-don-t-blindly-isolate-all-the-scopes-in-angularjs-directives.htm) about "Don't Blindly Isolate All The Scopes In AngularJS Directives".  So I have changed the code to not isolate scope.  Please update to v0.10.0 and reopen this ticket if you need further assistance.

Thanks a lot!
