### ISSUE TITLE
Allow dynamic currency-symbol

### ISSUE THREAD

**Issue by jjoekoullas** [aguirrel/ng-currency#77]
Hello,

I have an application which needs to work with different currencies at once (so this isn't something to solve with localization).  These currencies are user-entered.  I can't seem to find a way to use `currency-symbol` to properly retrieve the correct symbol as well as support changes on the fly.

`currency-symbol="{{getCurrency(myObject)}}"` works when the page is first loaded, but if `getCurrency(myObject)` begins returning a different value, it is never evaluated again.
`currency-symbol="{{getCurrency(myObject)}}"` causes the currency symbol to read "getCurrency(myObject)", instead of the more desirable return value.

The symbol does get updated when the contents of the input are rendered again.  My guess is adding a watch on currency-symbol would probably solve it.

**Comment by aguirrel** [comment]
Hi @jjoekoullas Sorry for delay.  Please, use $scope.$broadcast("currencyRedraw"); after you change currency symbol.  If you need further asistance please reopen this ticket.
