### ISSUE TITLE
currency-symbol with expression binding containing HTML

### ISSUE THREAD

**Issue by Friedoo** [aguirrel/ng-currency#78]
Works:
currency-symbol="\&euro;"

....but I'd like to have a dynamic currency symbol and here's the problem...

Does not work:
currency-symbol="{{dynamicCurrencySymbolHavingSomeHtmlInside}}"

it renders as \&euro; instead of &euro;

Any idea?
Thank you in advance!

**Comment by aguirrel** [comment]
Hi @Friedoo , 

Please, change from this

```javascript
currency-symbol="{{dynamicCurrencySymbolHavingSomeHtmlInside}}"
```

to this

```javascript
currency-symbol="{{dynamicCurrencySymbolHavingSomeHtmlInside | decode}}"
```

and add this filter to your app

```javascript
app.filter('decode', function() {
    return function(text) {
        return angular.element('<div>' + text + '</div>').text();
    };                  
});
```
