### ISSUE TITLE
Per-field currency-symbol 

### ISSUE THREAD

**Issue by saikatmohajan** [aguirrel/ng-currency#79]
I want to use different currency symbol for different fields. But the value of the currency symbol is being suppressed by the last one. e.g, if I use currency-symbol="$" in one field and in the later field if I use currency-symbol="৳", the earlier field shows ৳, instead of $

                <label class="item item-input">
					<span class="input-label">Total Cost ({{expense.currency}})</span>
					<input ng-model="expense.amount"
					       type="text" ng-currency currency-symbol="$"
					       ng-disabled="!editPOE || (expense.name=='lc_value_payable')">
				</label>

				<label class="item item-input">
					<span class="input-label">Exchange Rate</span>
					<input ng-model="expense.exchangeRate"
					       type="text" ng-currency currency-symbol="৳"
					       ng-disabled="!editPOE"
					       ng-change="onChangeExchangeRate(expense.amount, expense.exchangeRate)">
				</label>

				<label class="item item-input">
					<span class="input-label">Amount after exchange (BDT)</span>
					<input ng-model="expense.amountAfterExchange"
					       type="text" ng-currency currency-symbol="৳"
					       ng-disabled="true"
					       ng-change = "onChangeExchangeRate(expense.amount, expense.exchangeRate)">
				</label>

**Comment by aguirrel** [comment]
Yes, you are right.  It seems that problem appear at last update, please use 0.9.6 versión in the meantime.

**Comment by aguirrel** [comment]
Better, just update to v0.10.1 ;) Thanks!
