### ISSUE TITLE
Negative values

### ISSUE THREAD

**Issue by ulic75** [aguirrel/ng-currency#8]
It doesn't currently seem to support negative values either by entering -10 or (10).  I'd like to use this for an invoice application I've been fiddling with and need to be able to apply credits and such represented by negative values.

**Comment by tm0e83** [comment]
Negative value don't work for me. Even in your plunker example in the description all negative value are automatically converted to positive values.

**Comment by aguirrel** [comment]
hi @tm0e83 I will double check it.

Thanks!

**Comment by tm0e83** [comment]
Thank you! This is how you can reproduce it:

http://plnkr.co/edit/u9mJqDH8UpwxDnOv8gZL?p=preview

add a "-" before the number and it will disappear on blur.

**Comment by aguirrel** [comment]
Hi @tm0e83,

Please, use https://rawgit.com/aguirrel/ng-currency/master/src/ng-currency.js which is the current version (0.7.13). Link https://rawgit.com/aguirrel/ng-currency/master/src/ng-currency.js is outdated.

Please, check it again and reopen this issue if you have some problem.

Thanks! :)
