### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by qlonik** [aguirrel/ng-currency#80]
Hello. 

NPM does not automatically pick up tags as bower. However, could you still publish it to npm?

Thanks!

**Comment by aguirrel** [comment]
Do you have any howto to know how can I do it?

**Comment by qlonik** [comment]
I think simple `npm publish` should be enough.

I'm sorry if I said it wrong. I meant that bower automatically finds new versions of packages, if git tag is created. However, npm does not work like this. To publish in npm, it has to be done explicitly with `npm publish`.

It is likely possible to do git hook on git tag command to publish the package. However, I don't know how to do those things.

**Comment by aguirrel** [comment]
Done! Thanks a lot!
