### ISSUE TITLE
Input reset the value if setting fraction to "0" on Europe local (€)

### ISSUE THREAD

**Issue by itaibaruch** [aguirrel/ng-currency#84]
Hi,

First of all VERY nice solution to the problems of input fields that have currency.

I come across a strange behavior in Europe local. 
If I set the input fraction "0", when I click on the input and blur out I get different results.
most of the time it just reset to the initial value.

If I change the the default value to "0" in the library like so:
`scope.fraction = (typeof scope.fraction !== 'undefined')?scope.fraction:0;`
it solve the problem, but via the attribute I just get this bug.

The bug don't happened with $.

Thanks.

**Comment by itaibaruch** [comment]
I see someone had the same problem :)
https://github.com/oriolcp/ng-currency/commit/12b72f61c080ffc0e06afe0ad370d785250a6e9f

**Comment by oriolcp** [comment]
Hey,
  
I've just fixed on #83

**Comment by aguirrel** [comment]
Hi guys, thanks a lot @oriolcp!  

@itaibaruch could you use master branch to test if this solution works for you?

**Comment by aguirrel** [comment]
Hi @itaibaruch, silence gives consent  ;)  , so I'm closing this ticket.

Please reopen this ticket if you need further assistance.
