### ISSUE TITLE
Problem: How to reset the ng-currency input invalid value?

### ISSUE THREAD

**Issue by wangzhenyu1260** [aguirrel/ng-currency#87]
I want to reset the ng-currency invalid input, but the invalid value still exist. You can give me a example about resetting ng-currency input.

**Comment by aguirrel** [comment]
Hi @wangzhenyu1260 , I think deleting content of $error in your input should work.  You can find $error in formName.inputName.$error (form name is your form name, the same for input).

Please reopen this ticket if you need further assistance.
