### ISSUE TITLE
Technical Debt: Run Tests on each PR and Commit

### ISSUE THREAD

**Issue by nick-woodward** [aguirrel/ng-currency#88]
* Add a .travis.yml file to run unit tests and linting

**Comment by aguirrel** [comment]
Hi Nick!

Thaks a lot! I have just added Travis support.  I can't see how to linting with Travis, could you recomend me some tools for that?

Best regards.

**Comment by nick-woodward** [comment]
Sure, I generally use eslint for linting purposes due to its support for linting ES6.

Here's a quick start repo I created for angular components but the same concepts should apply:
https://github.com/salte-io/salte-seed

If you want I can submit a PR tonight to implement some of the features in the repository I linked.

**Comment by aguirrel** [comment]
Hi Nick!

NP about description.  Yes! I would be great if you submit a PR with this! 

Thanks a lot!
