### ISSUE TITLE
Feature: Add support for hard caps

### ISSUE THREAD

**Issue by nick-woodward** [aguirrel/ng-currency#89]
We need the ability to force a user to be between the min and max values.

e.g. a user enters -300 and the min is 0. When the user deselects the field the value should be set to 0.

**Comment by aguirrel** [comment]
Hi Nick!  I don't think this behavior should be implemented in this directive as it's very specific and could broke someone else development.  Please, add a watch to directive error values.  You can access using formName.inputName.$error.

Please reopen this ticket if you need further assistance.

**Comment by nick-woodward** [comment]
I can totally understand why you'd want to keep this feature separate from the original intention of the directive.

Would you be opposed to disabling the feature by default and having a way to toggle it on?

**Comment by aguirrel** [comment]
It would be cool to have this feature, if it's disabled by default.  If you have some code to add just make a PR and I will check it.  If you can add some test cases too could be great!

Thanks a lot!

**Comment by nick-woodward** [comment]
@aguirrel Awesome sound good! Can you reopen this issue?

**Comment by aguirrel** [comment]
Yes of course!
