### ISSUE TITLE
Bug: Remove Isolated Scope

### ISSUE THREAD

**Issue by nick-woodward** [aguirrel/ng-currency#90]
There's no reason to have an isolated scope on this directive.

**Comment by aguirrel** [comment]
Hi Nick! Thanks for the advice.  Actually was not a bug but a design desition.  Anyway it was changed in version 0.10.x.  Please upgrade to have non-isolated scope.

Best regards.

**Comment by nick-woodward** [comment]
Just to clarify, are you saying that the directive does or doesn't have an isolated scope?
https://github.com/aguirrel/ng-currency/blob/master/src/ng-currency.js#L18

**Comment by aguirrel** [comment]
Hi Nick,

Directive doesn't have an isolated scope.  It was changed by #75 Avoid using isolated scope.

**Comment by nick-woodward** [comment]
The isolated scope was removed in: https://github.com/aguirrel/ng-currency/commit/bc0e717b93eb1e017e1121c2acf08e217f17dc30

However it was added back for some reason in: https://github.com/aguirrel/ng-currency/commit/547c9fe4159730b42277b597c5f700f2d385fc72

The following are examples of isolated scopes:
```javascript
scope: {}
scope: true
```
Removing scope from the directive or setting it to false would get rid of the isolated scope.

As an example change:
```js
restrict: 'A',
require: 'ngModel',
link: function (scope, elem, attrs, ngModel) {
```
To:
```js
restrict: 'A',
require: 'ngModel',
scope: {},
link: function (scope, elem, attrs, ngModel) {
```
At: https://github.com/aguirrel/ng-currency/blob/master/test/ng-currency.test.js#L23

The run the tests.

It should complain about multiple directives, "ngCurrency" and "centsToDollars" attempting to create isolated scopes.

**Comment by aguirrel** [comment]
I remember now.  If I remove scope: {} from directive, you can't use many ng-currency directive in differents configurations.  For example, if you need one input with currency-symbol='$' and another with currency-symbol='€' it just doesn't work, and I didn't investigate enough  to solve it.  Do you have any clue about that?

**Comment by nick-woodward** [comment]
Yup, if you remove the isolated scope then scope becomes the parent scope. 

The solution is to move all values that you're binding to scope to local variables. 
I can open a PR for this as well!

**Comment by aguirrel** [comment]
Yes please. Thanks a lot!
